name: emseg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy==2.4.3
    - zarr==2.18.7
    - dask==2026.3.0
    - scikit-image==0.26.0
    - matplotlib==3.10.8
    - s3fs
    - torch
    - torchvision
    - Pillow
    - scikit-learn
    - transformers
    - jupyter
